name: Translate resume files

on:
  push:
    paths:
      - 'resume.i18n.json'

jobs:
  split-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Language-Specific Files
        run: |
          node .github/scripts/split-languages.js

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.en.json resume.fr.json
          git commit -m "chore: update language-specific resume files" || exit 0
          git push

      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          gh gist edit $GIST_ID resume.json < resume.en.json
