name: Translate resume files

on:
  push:
    paths:
      - 'resume.i18n.json'
  workflow_dispatch:

jobs:
  split-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Translate resume files
      - name: Create Language-Specific Files
        run: |
          node .github/scripts/split-languages.js

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.en.json resume.fr.json
          git commit -m "chore: update language-specific resume files" || exit 0
          git push

      # Update gist resume.json : https://gist.github.com/ludoo0d0a/b7e4355cd0d2722f25002eca525ea262
      # to see changes into jsonresume.org website : https://registry.jsonresume.org/ludoo0d0a
      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          gh gist edit $GIST_ID -f resume.json resume.en.json

      # Deploy to GitHub Pages
      - name: Install Resume CLI
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-kendall

      - name: Generate HTML
        run: |
          resume export index.html --theme kendall --resume resume.en.json
          resume export index-fr.html --theme kendall --resume resume.fr.json

      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-html
          path: |
            index.html
            index-fr.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #personal_token: ${{ secrets.GHP_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          enable_jekyll: false

      - name: Log Deploy URL
        run: |
          echo "::notice::Resume deployed to https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

